spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/reactlibrarydatabase?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.data.rest.base-path=/api

## Auth0 configuration (issuer URL must end with "/")
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI:https://dev-58r52o8fx5djc8od.us.auth0.com/}
spring.security.oauth2.resourceserver.jwt.audiences=${AUTH0_AUDIENCE:https://luv2read-api}

stripe.key.secret=${STRIPE_SECRET_KEY}

#####
#
# HTTPS configuration
#
#####
# Server web port
server.port=8443
# Enable HTTPS support (only accept HTTPS requests)
server.ssl.enabled=true
# Alias that identifies the key in the key store
server.ssl.key-alias=luv2code
# Keystore location
server.ssl.key-store=classpath:luv2code-keystore.p12
# Keystore password
server.ssl.key-store-password=secret
# Keystore format
server.ssl.key-store-type=PKCS12